name: buy_flow
description: "A mobile app that handles purchases management."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1

  # Maps + address
  location: ^7.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1

  # QR generation / scan
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.1

  # PDF download/share
  printing: ^5.13.0
  path_provider: ^2.1.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/logo-buyflow-design.png
    - lib/assets/logo-buyflow.png

